### ISSUE TITLE
Error "Puli Factory is not available"

### ISSUE THREAD

**Issue by JensKirk** [RiskioFr/clearhaus-sdk-php#7]
Hi :-)

I get this error. What to do here?

`Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - Puli Factory is not available - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Symfony\Component\HttpClient\HttplugClient, Http\Adapter\Guzzle6\Client, Http\Adapter\Guzzle5\Client, Http\Client\Curl\Client, Http\Client\Socket\Client, Http\Adapter\Buzz\Client, Http\Adapter\React\Client, Http\Adapter\Cake\Client, Http\Adapter\Zend\Client, Http\Adapter\Artax\Client, Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate. - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: . in /home/ecoapp/public_html/administrator/components/com_economic/api/clearhaus/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41 Stack trace: #0 /home in /home/............/clearhaus/vendor/php-http/discovery/src/HttpClientDiscovery.php on line 27`

We are using PHP 7.3.

**Comment by neeckeloo** [comment]
The SDK is based on HTTPlug that allows to write reusable libraries and applications that need an HTTP client without binding to a specific implementation. Consequently, you have to require the client library of your choice in your application. For instance, you can use Guzzle:

`composer require php-http/curl-client guzzlehttp/psr7`

http://docs.php-http.org/en/latest/discovery.html#common-errors
